In [ ]:
#_________________________________________________________________________________________________________________________#
#______________________________________________________Raven.ai___________________________________________________________#
#_________________________________________________________________________________________________________________________#

In [ ]:
import numpy as np

In [ ]:
dataset = np.array([1.0, 12.4, 140 ])

In [ ]:
normalized_dataset = (dataset - np.min(dataset))/(
    np.max(dataset) - np.min(dataset))

print(normalized_dataset)

[0.         0.08201439 1.        ]


In [ ]:
dataset = np.array([1.0, 2.0, 3.0, 4.0, 5.0])

In [ ]:
standardized_dataset = (dataset - np.average(dataset)) / (
    np.std(dataset))

print(standardized_dataset)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [ ]:
import numpy as np

data = np.array(['small', 'medium', 'large', 'xlarge'])

from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
data_encoded = encoder.fit_transform(data)

print(data_encoded)


[2 1 0 3]


In [ ]:
import numpy as np

data = np.array(['red', 'blue', 'black', 'white'])

from sklearn.preprocessing import LabelBinarizer
encoder = LabelBinarizer()
data_encoded = encoder.fit_transform(data)

print(data_encoded)


[[0 0 1 0]
 [0 1 0 0]
 [1 0 0 0]
 [0 0 0 1]]
